name: functions_ex
on: workflow_dispatch
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: contains test
      if: contains('sandeep mishra', 'ee')
      run: echo "name is sandeep"
    - name: startswith test
      if: startsWith('sandeep mishra', 'sa')
      run: echo "name is sandeep"
    - name: endswith test
      if: endsWith('sandeep mishra', 'ra')
      run: echo "name is sandeep"

